#spring-boot-starter-mail properties
spring:
  mail:
    host: smtp.office365.com
    port: 587
    username: "your e-mail"
    password: "your password"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
    test-connection: true
